name: Deploy gotoHuman demo worker
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: echo "Job to deploy was automatically triggered by a ${{ github.event_name }} event in your repo ${{ github.repository }}."
      - uses: actions/checkout@v4
      - name: Build & Deploy gotoHuman demo worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

